apiVersion: v1
kind: Secret
metadata:
  name: sys-secrets
type: Opaque
data:
  telegram-bot-token: telegram-bot-token
  dadata-api-key: dadata-api-key
  db-username: db-username
  db-password: db-password
  broker-username: broker-username
  broker-password: broker-password