apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
  labels:
    app: web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
        - name: web-ui
          image: company-name/web-ui
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sys-secrets
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sys-secrets
                  key: db-password
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: sys-config-params
                  key: db-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: sys-config-params
                  key: db-port
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
      restartPolicy: Always
